[package]
name = "wk-sim"
version.workspace = true
edition.workspace = true

[dependencies]
wk-material = { path = "../wk-material" }
wk-world = { path = "../wk-world" }
wk-field = { path = "../wk-field" }
wk-agents = { path = "../wk-agents" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
wk-io = { path = "../wk-io" }

[[test]]
name = "scenarios"
path = "../../tests/scenarios/mod.rs"
